port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
mode: Rule
log-level: warning
ipv6: false
udp: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 168
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/Country.mmdb"
profile:
  store-selected: true
  store-fake-ip: true
hosts:
  raw.githubusercontent.com: [185.199.108.133, 185.199.109.133, 185.199.110.133, 185.199.111.133, "2606:50c0:8000::154", "2606:50c0:8001::154", "2606:50c0:8002::154", "2606:50c0:8003::154"]
  doh.pub: [1.12.12.21, 120.53.53.53, "2402:4e00::", "2402:4e00:1::"]
  dns.alidns.com: [223.5.5.5, 223.6.6.6, "2400:3200::1", "2400:3200:baba::1"]
  dns.google: [8.8.4.4, 8.8.8.8, "2001:4860:4860::8844", "2001:4860:4860::8888"]
  cloudflarr-dns.com: [1.0.0.1, 1.1.1.1, "2606:4700:4700::1001", "2606:4700:4700::1111"]
  dns.cloudflare.com: [1.0.0.1, 1.1.1.1, "2606:4700:4700::1001", "2606:4700:4700::1111"]
dns:
  enable: true
  listen: '0.0.0.0:1053'
  ipv6: false
  prefer-h3: false
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['GEOSITE:private,connectivity-check']
  nameserver-policy:
    'GEOSITE:category-ads-all,category-httpdns-cn': rcode://name_error
    'GEOSITE:cn,apple,microsoft':
      - 'https://dns.alidns.com/dns-query#DIRECT&h3=true'
      - 'https://doh.pub/dns-query#DIRECT'
    'GEOSITE:geolocation-!cn':
      - 'https://dns.google/dns-query#Google&h3=true'
      - 'https://cloudflare-dns.com/dns-query#Cloudflare&h3=true'
  direct-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  proxy-server-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - 'https://dns.alidns.com/dns-query#DIRECT&h3=true'
    - 'https://doh.pub/dns-query#DIRECT'
proxy-providers:
  KTV:
    type: http
    interval: 43200
    health-check:
      enable: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600
      timeout: 2000
    path: ./proxy_provider/KTV.yaml
    url: "https://****"
  SNTP:
    type: http
    interval: 43200
    health-check:
      enable: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600
      timeout: 2000
    path: ./proxy_provider/SNTP.yaml
    url: "https://****"
  BaiduN:
    type: http
    interval: 43200
    health-check:
      enable: true
      url: "https://wifi.vivo.com.cn/generate_204"
      interval: 600
      timeout: 2000
    path: ./proxy_provider/BaiduProxy.yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/ProxyConfigFiles/refs/heads/main/Mihomo/BaiduProxy.yaml"
proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}
proxy-groups:
  - name: Location
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bypass.png"
    type: select
    proxies: [ç›´è¿, æ±Ÿè‹, åŒ—äº¬, å¹¿ä¸œ, æµ™æ±Ÿ, æ²³åŒ—]
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: false
  - name: Domestic
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Domestic.png"
    type: select
    proxies: [ç›´è¿, æ±Ÿè‹, åŒ—äº¬, å¹¿ä¸œ, æµ™æ±Ÿ, æ²³åŒ—]
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: false
  - name: Tiktok
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok_2.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Youtube
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Media
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ForeignMedia.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Openai
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Telegram
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Cloudflare
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Cloudflare.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Google
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Github
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/GitHub.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Microsoft
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Apple
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Foreign
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: Final
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png"
    type: select
    proxies: [ç›´è¿, é¦™æ¸¯, å°æ¹¾, ç‹®åŸ, æ—¥æœ¬, ç¾å›½, ä½å€, é«˜å€]
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: false
  - name: æ±Ÿè‹
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Surge(1).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: true
    filter: "å—äº¬|è‹å·"
  - name: åŒ—äº¬
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Surge(2).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: true
    filter: "åŒ—äº¬"
  - name: å¹¿ä¸œ
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Surge(4).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: true
    filter: "å¹¿å·"
  - name: æµ™æ±Ÿ
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Surge(3).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: true
    filter: "æµ™æ±Ÿ"
  - name: æ²³åŒ—
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Surge(5).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://wifi.vivo.com.cn/generate_204"
    interval: 300
    hidden: true
    filter: "ä¿å®š"
  - name: é¦™æ¸¯
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '(?i)(?:æ¸¯|é¦™æ¸¯|ğŸ‡­ğŸ‡°|\bHK\b|Hong|HKG)'
  - name: å°æ¹¾
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '(?i)(?:å°|å°æ¹¾|ğŸ‡¼ğŸ‡¸|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|\bTW\b|tai|TWN)'
  - name: ç‹®åŸ
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '(?i)(?:å¡|æ–°åŠ å¡|ğŸ‡¸ğŸ‡¬|\bSG\b|Singapore|SGP)' 
  - name: æ—¥æœ¬
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '(?i)(?:æ—¥|æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|\bJP\b|Japan|JPN)'
  - name: ç¾å›½
    icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '(?i)(?:ç¾|ç¾å›½|ğŸ‡ºğŸ‡¸|\bUS\b|USA|States)'
  - name: ä½å€
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/liuliang(2).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '0\.\d+'
  - name: é«˜å€
    icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/liuliang(3).png"
    include-all-providers: true
    type: smart
    uselightgbm: true
    collectdata: false
    strategy: sticky-sessions
    prefer-asn: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    hidden: true
    filter: '(?!0\.)[1-9]\d*(?:\.\d+)'
rule-providers:
  awavenue:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"
    path: ./rule_provider/awavenue.mrs
  mydirect:
    type: http
    behavior: domain
    interval: 86400
    format: yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/ProxyConfigFiles/refs/heads/main/Mihomo/rule/Direct.yaml"
    path: ./rule_provider/mydirect.yaml
  myrejectdomain:
    type: http
    behavior: domain
    interval: 86400
    format: yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/ProxyConfigFiles/refs/heads/main/Mihomo/rule/Reject_domain.yaml"
    path: ./rule_provider/myrejectdomain.yaml
  myrejectip:
    type: http
    behavior: ipcidr
    interval: 86400
    format: yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/ProxyConfigFiles/refs/heads/main/Mihomo/rule/Reject_ip.yaml"
    path: ./rule_provider/myrejectip.yaml
  myproxy:
    type: http
    behavior: domain
    interval: 86400
    format: yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/ProxyConfigFiles/refs/heads/main/Mihomo/rule/Proxy.yaml"
    path: ./rule_provider/myproxy.yaml
  emby:
    type: http
    behavior: domain
    interval: 86400
    format: yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/ProxyConfigFiles/refs/heads/main/Mihomo/rule/Emby.yaml"
    path: ./rule_provider/emby.yaml
  fakelocation:
    type: http
    behavior: classical
    interval: 86400
    format: yaml
    url: "https://raw.githubusercontent.com/MeALiYeYe/anti-ip-attribution/refs/heads/main/generated/rule-provider.yaml"
    path: ./rule_provider/fakelocation.yaml
rules:
  - RULE-SET,awavenue,REJECT
  - RULE-SET,myrejectdomain,REJECT
  - RULE-SET,myrejectip,REJECT,no-resolve
  - RULE-SET,fakelocation,Location
  - RULE-SET,mydirect,DIRECT
  - RULE-SET,myproxy,Foreign
  - RULE-SET,emby,Media
  - GEOSITE,private,DIRECT 
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,category-httpdns-cn,REJECT
  - GEOSITE,youtube,Youtube
  - GEOSITE,tiktok,Tiktok
  - GEOSITE,category-entertainment,Media
  - GEOSITE,telegram,Telegram
  - GEOSITE,google,Google
  - GEOSITE,cloudflare,Cloudflare
  - GEOSITE,category-ai-!cn,Openai
  - GEOSITE,github,Github
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,apple,Apple
  - GEOSITE,geolocation-!cn,Foreign
  - GEOSITE,cn,Domestic
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,Telegram,no-resolve
  - GEOIP,google,Google,no-resolve
  - GEOIP,cloudflare,Cloudflare,no-resolve
  - GEOIP,cn,Domestic,no-resolve
  - MATCH,Final
