name: Sync Multiple Gists to Repo

on:
  schedule:
    - cron: '33 19 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Sync Gist files
        run: |
          files=(
            "https://gist.githubusercontent.com/MeALiYeYe/42151e8055f111208c92971fca6e25ce/raw/d57f81f4c75d39ee4f0aeab4c47314646a53d684/config.yaml Mihomo/Alpha/config.yaml"
            "https://gist.githubusercontent.com/MeALiYeYe/42151e8055f111208c92971fca6e25ce/raw/d57f81f4c75d39ee4f0aeab4c47314646a53d684/Egern.yaml Egern/Egern.yaml"
            "https://gist.githubusercontent.com/MeALiYeYe/42151e8055f111208c92971fca6e25ce/raw/d57f81f4c75d39ee4f0aeab4c47314646a53d684/Surge.conf Surge/Surge.conf"
          )

          for file in "${files[@]}"; do
            url=$(echo $file | awk '{print $1}')
            dest=$(echo $file | awk '{print $2}')
            mkdir -p $(dirname "$dest")
            curl -sL "$url" -o "$dest"
            git add "$dest"
          done

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --cached --quiet || git commit -m "Sync multiple Gist files"
          git push
